/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import patterns.Ellipse;
import patterns.IBrush;
import patterns.MainFrame;
import patterns.Rectangle;
import patterns.Shape;
import patterns.SolidBrush;
import patterns.TextureBrush;


/**
 *
 * @author aluno
 */
public class MainFrameBridge extends javax.swing.JFrame {
    private IBrush selectedBrush = null;
    private Shape selectedShape = null;
    private MainFrame mainframe;
    /**
     * Creates new form MainFrameOriginal
     */
    public MainFrameBridge() {
        initComponents();
        Shape ellipse = new Ellipse();
        Shape rect = new Rectangle();
        IBrush solidBrush = new SolidBrush();
        IBrush textureBrush = new TextureBrush();
        AbstractBridge.addItem(solidBrush.toString());
        AbstractBridge.addItem(textureBrush.toString());
        ImplementationBridge.addItem(rect.toString());
        ImplementationBridge.addItem(ellipse.toString());
        this.selectedBrush = new SolidBrush();
        this.selectedShape = new Rectangle();
    }
    
    public void paint() {
        if(mainframe == null) {
            this.mainframe = new MainFrame(selectedBrush, selectedShape);
            this.mainframe.setVisible(true);
        } else {
            this.mainframe.dispose();
            this.mainframe = new MainFrame(selectedBrush, selectedShape);
            mainframe.setVisible(true);
        }
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AbstractBridge = new javax.swing.JComboBox<>();
        ImplementationBridge = new javax.swing.JComboBox<>();
        BotaoBridge = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bridge");

        AbstractBridge.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        AbstractBridge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbstractBridgeActionPerformed(evt);
            }
        });

        ImplementationBridge.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        ImplementationBridge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImplementationBridgeActionPerformed(evt);
            }
        });

        BotaoBridge.setText("Desenhar");
        BotaoBridge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoBridgeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AbstractBridge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ImplementationBridge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(BotaoBridge)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AbstractBridge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ImplementationBridge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(BotaoBridge)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AbstractBridgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbstractBridgeActionPerformed
        if(AbstractBridge.getSelectedItem() == "SolidBrush") 
            this.selectedBrush = new SolidBrush();
         else 
            this.selectedBrush = new TextureBrush();

    }//GEN-LAST:event_AbstractBridgeActionPerformed

    private void ImplementationBridgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImplementationBridgeActionPerformed
         if(ImplementationBridge.getSelectedItem() == "Rectangle") 
            this.selectedShape = new Rectangle();
         else 
            this.selectedShape = new Ellipse();
    }//GEN-LAST:event_ImplementationBridgeActionPerformed

    private void BotaoBridgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoBridgeActionPerformed
        this.paint();
    }//GEN-LAST:event_BotaoBridgeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrameBridge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrameBridge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrameBridge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrameBridge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrameBridge().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AbstractBridge;
    private javax.swing.JButton BotaoBridge;
    private javax.swing.JComboBox<String> ImplementationBridge;
    // End of variables declaration//GEN-END:variables
}
