/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package blok.gui;

import blok.simulator.ISimulator;
import java.awt.Dimension;

/**
 *
 * @author sandroandrade
 */
public class MainWindow extends javax.swing.JFrame {
    private GameAbstract game; 
    private ISimulator simulator;
    /**
     * Creates new form MainWindow
     */
    public MainWindow(GameAbstract game, ISimulator simulator) {
        initComponents();
        Dimension size = new Dimension(900, 600);

        GameAbstract mainPanel = game;
        mainPanel.setPreferredSize(size);
        mainPanel.setMinimumSize(size);
        mainPanel.setMaximumSize(size);
        mainPanel.setSize(size);
        setContentPane(mainPanel);

        setResizable(false);
        pack();
        
        ISimulator simulator2 = simulator;
        mainPanel.setSimulator(simulator);
        simulator.init();
        //simulator.start();
        this.game = game;
        this.simulator = simulator;
    }
    
    public void resetar() {
        if(this.game.m_state == GameAbstract.State.RUNNING) {
            this.game.m_simulator.stop();
            this.simulator.stop();
        }
        this.simulator = null;
        this.game = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
