/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package retirado;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import patterns.Ellipse;
import patterns.IBrush;
import patterns.IBrush;
import patterns.Rectangle;
import patterns.Shape;
import patterns.Shape;
import patterns.SolidBrush;
import patterns.TextureBrush;
import sun.java2d.opengl.OGLRenderQueue;

/**
 *
 * @author aluno
 */
public class MyPanel extends javax.swing.JPanel {    
    IBrush selectedBrush = null;
    Shape selectedShape = null;
    /**
     * Creates new form PanelBridge
     */
    public MyPanel(IBrush selectedBrush, Shape selectedShape) {
        this.selectedBrush = selectedBrush;
        this.selectedShape = selectedShape;
        initComponents();
    }
    
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        RenderingHints rh = new RenderingHints(
           RenderingHints.KEY_ANTIALIASING,
           RenderingHints.VALUE_ANTIALIAS_ON);

        rh.put(RenderingHints.KEY_RENDERING,
              RenderingHints.VALUE_RENDER_QUALITY);

        g2d.setRenderingHints(rh); 
        selectedShape.setBrush(selectedBrush);
        selectedShape.draw(300, 50, 200, 100, g2d);
        

//
//        Shape rect = new Rectangle();
//        IBrush brush = new SolidBrush();
//        rect.setBrush(brush);
//        rect.draw(300, 50, 200, 100, g2d);
//        
//        Shape ellipse = new Ellipse();
//        ellipse.setBrush(brush);
//        ellipse.draw(300, 250, 200, 100, g2d);
//        
//        IBrush brush2 = new TextureBrush();
//        
//        Shape rect2 = new Rectangle();
//        rect2.setBrush(brush2);
//        rect2.draw(600, 50, 200, 100, g2d);
//        
//        Shape ellipse2 = new Ellipse();
//        ellipse2.setBrush(brush2);
//        ellipse2.draw(600, 250, 200, 100, g2d);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMinimumSize(new java.awt.Dimension(300, 300));
        setPreferredSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
